
import java.util.ArrayList;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author agln7
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregarCarpeta = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        tf_nombreCarpeta = new javax.swing.JTextField();
        crearCarpeta = new javax.swing.JButton();
        jd_AgregarArchivo = new javax.swing.JDialog();
        tf_nombreArchivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_ext = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tf_tamanoArchivo = new javax.swing.JTextField();
        crearArchivo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jLabel1.setText("Nombre");

        crearCarpeta.setText("Crear Carpeta");
        crearCarpeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearCarpetaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarCarpetaLayout = new javax.swing.GroupLayout(jd_agregarCarpeta.getContentPane());
        jd_agregarCarpeta.getContentPane().setLayout(jd_agregarCarpetaLayout);
        jd_agregarCarpetaLayout.setHorizontalGroup(
            jd_agregarCarpetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarCarpetaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jd_agregarCarpetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crearCarpeta)
                    .addComponent(tf_nombreCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jd_agregarCarpetaLayout.setVerticalGroup(
            jd_agregarCarpetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarCarpetaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jd_agregarCarpetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombreCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(crearCarpeta)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jLabel2.setText("Nombre");

        jLabel3.setText("Extension");

        cb_ext.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "pdf", "txt", "docx", "mp4" }));

        jLabel4.setText("Tamano");

        crearArchivo.setText("Crear Archivo");
        crearArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearArchivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_AgregarArchivoLayout = new javax.swing.GroupLayout(jd_AgregarArchivo.getContentPane());
        jd_AgregarArchivo.getContentPane().setLayout(jd_AgregarArchivoLayout);
        jd_AgregarArchivoLayout.setHorizontalGroup(
            jd_AgregarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarArchivoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jd_AgregarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45)
                .addGroup(jd_AgregarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crearArchivo)
                    .addComponent(tf_tamanoArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_ext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jd_AgregarArchivoLayout.setVerticalGroup(
            jd_AgregarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarArchivoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jd_AgregarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(jd_AgregarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_ext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jd_AgregarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_tamanoArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(crearArchivo)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("listar Carpetas y Archivos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Mi Unidad");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Destacados");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Papelera");
        jMenu1.add(jMenuItem3);

        jMenu2.setText("Agregar");

        jMenuItem4.setText("Carpeta");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Archivo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addContainerGap(1103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jButton1)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearCarpetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearCarpetaMouseClicked
        String nombre = tf_nombreCarpeta.getText();

        Random r = new Random();
        int random = 10000 + r.nextInt(99999);
        String linkaux = "dive.google.com/"+random;

        Carpeta c = new Carpeta(nombre, linkaux);
        carpetas.add(c);
        tf_nombreCarpeta.setText("");
        jd_agregarCarpeta.dispose();
    }//GEN-LAST:event_crearCarpetaMouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jd_agregarCarpeta.pack();
        jd_agregarCarpeta.setLocationRelativeTo(this);
        jd_agregarCarpeta.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jd_AgregarArchivo.pack();
        jd_AgregarArchivo.setLocationRelativeTo(this);
        jd_AgregarArchivo.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void crearArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearArchivoMouseClicked

        String nombre = tf_nombreArchivo.getText();
        String extension = (String) cb_ext.getSelectedItem();
        int tamano = Integer.parseInt(tf_tamanoArchivo.getText());
        Random r = new Random();
        int random = 10000 + r.nextInt(99999);
        String linkaux = "dive.google.com/"+random;
        Archivo a = new Archivo(nombre, linkaux, extension, tamano);
        archivos.add(a);
        tf_nombreArchivo.setText("");
        tf_tamanoArchivo.setText("");
        cb_ext.setSelectedItem(" ");
        jd_AgregarArchivo.dispose();
    }//GEN-LAST:event_crearArchivoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Carpeta c = new Carpeta();
        System.out.println("Carpetas: ");
        for (int i = 0; i < carpetas.size(); i++) {
            System.out.println(carpetas.get(i));
        }
        System.out.println("");
        System.out.println("Archivos:");
        for (int i = 0; i < archivos.size(); i++) {
            System.out.println(archivos.get(i) + archivos.get(i).getLink());
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_ext;
    private javax.swing.JButton crearArchivo;
    private javax.swing.JButton crearCarpeta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JDialog jd_AgregarArchivo;
    private javax.swing.JDialog jd_agregarCarpeta;
    private javax.swing.JTextField tf_nombreArchivo;
    private javax.swing.JTextField tf_nombreCarpeta;
    private javax.swing.JTextField tf_tamanoArchivo;
    // End of variables declaration//GEN-END:variables
    ArrayList <Carpeta> carpetas = new ArrayList();
    ArrayList <Archivo> archivos = new ArrayList();

}
